name: pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: 12
          cache: yarn
      - uses: rlespinasse/github-slug-action@v3.x
      - run: yarn install
      - run: yarn build-storybook
      - name: Set destination dir
        id: set_destination_dir
        run: |
          if [[ $GITHUB_REF_SLUG == 'master' ]]; then
            echo "::set-output name=dir::"
          else
            echo "::set-output name=dir::$GITHUB_REF_SLUG"
          fi
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          destination_dir: ${{ steps.set_destination_dir.outputs.dir }}
          keep_files: true
